apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "custom-error-pages.fullname" . | quote }}
  namespace: {{ .Values.namespace | quote }}
data:
  404.html: |
{{ .Values.html.error404 | indent 4 }}
  500.html: |
{{ .Values.html.error500 | indent 4 }}
  502.html: |
{{ .Values.html.error502 | indent 4 }}
  503.html: |
{{ .Values.html.error503 | indent 4 }}
  504.html: |
{{ .Values.html.error504 | indent 4 }}
  default.conf: |
    server {
        listen 80;
        root /usr/share/nginx/html;

        location / {
            # Default to 404
            set $x_code "404";
            if ($http_x_code = "500") { set $x_code "500"; }
            if ($http_x_code = "502") { set $x_code "502"; }
            if ($http_x_code = "503") { set $x_code "503"; }
            if ($http_x_code = "504") { set $x_code "504"; }

            try_files /$x_code.html /404.html;
        }
    }
