{{- if .Values.secretFrom }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litellm-proxy.fullname" . }}-secrets
  labels:
    {{- include "litellm-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secretFrom | nindent 2 }}
{{- end }}
