version: "3"

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    network_mode: "host"
    environment:
      TZ: Africa/Johannesburg
      WEBPASSWORD: admin
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
