n8n:  # <--- Everything must be nested under this key
  service:
    type: NodePort
    port: 5678
    nodePort: 30082
  config:
    database:
      type: postgresdb
      postgres:
        host: "postgres-postgresql.storage.svc.cluster.local"
        port: 5432
        database: n8n
        user: n8n
        existingSecret: "postgres-credentials"
        existingSecretPasswordKey: "password"
  spec:
    source:
      path: .  # Path to folder with Chart.yaml
      helm:
        valueFiles:
          - "../values.yaml" # Your indented values.yaml
