primary:
  persistence:
    enabled: true
    size: 5Gi
    storageClass: standard

auth:
  username: postgres
  database: n8n

  existingSecret: postgres-secret

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 500Mi