primary:
  persistence:
    enabled: true
    size: 5Gi
    storageClass: standard

auth:
  username: n8n
  database: n8n

  existingSecret: postgres-credentials
  secretKeys:
    adminPasswordKey: password
    userPasswordKey: password

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 500Mi