primary:
  persistence:
    enabled: true
    size: 5Gi
    storageClass: standard

auth:
  postgresPassword: ""
  username: n8n
  password:
    existingSecret: postgres-credentials
    existingSecretPasswordKey: password
  database: n8n

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi