apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: management
spec:
  encryptedData:
    .dockerconfigjson: AgBCzI26n7iIGFM9uoPYLuZCnbzqUC/seibVD08wH7+owrNck83fHtRxDHmv3SNO5estbx7TcYonnMfqIq+DohtO2iHjcsBhk+gPx/ICQdF4CIR8Ija3085HrUW69qwDPy6CptkOLK6YPs6d+pDhWdnI+zWTvyhTMGwD6Nmwn5fWeJJzwgclSqv0DCkHVdY2wes3QAypCTCFrCQMybtowYoNK3I4JV5VOz4KXSR3QaZ5bjx0UvgYFVVL82LOB1dXzmJouAH/ueZKIci9YincSC9LOW2E+Sp7LJcMO9VsMLWjP2e8IqF96b5pxkn/icdgtNQYpBrAn5PQBdFCXjx2BfaqhzEv4kKT4ZnJPUZCEK2f8HHX+2mD4I7VQKOhKXeuxlR0gheH8/TcT++JUnQsXQnXUxexFK/qdg87qs+D4nkogzh4q/klRtTgCMu7diLS2juMWTuDYMHqCP9ExDzxmn6PLiS5vgN6UvCHvOpEP+BSre95oc1d8NFPh6s4Ol3awXule76igFnq5ETOmCCPA3TkjwwGDl12NLf9A7RoLR0e+0PVVSi0kXatspLA43bSBigAzc/Vfkb5Ta6Msk3GNDWy+f2l5kUuZF/dcd07qiNAQMTZJ8VI+BB1iluFH/1wR12gwhEWrcMy+rfKNXmX4mJhM8xfTc9iXdtjCzWp/CNR3v3IFT3yLMVVHBFS7GFR2wJYyysOXJvccvLEd+ZnvEWip8mDoAZaeRLnlw5iDrOC78GzwJsdLasr6fY9SZ2/e+T7/XSVZj1sm5AsVfgJDrBha/1rqN57edb7QTzMBGorEBhaCjArYslxqqCJz2wBj3i6/FKHPZfttUWWMfv6ovIEgsA4b07rnt1r/OqjxhwZ8mDFo36Tdbbe8ZHmGb21m0/4YN2HFnEFrKwLIeIW9Pz72VT4yVh5/bi5Mw76Xmv4b7Y1vZLVgkhmyw7C9uhAF//K73y311gweWggUQwU7duMlgIHuEFImTw=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: management
    type: kubernetes.io/dockerconfigjson