apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ginger
  namespace: applications
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: applications
  source:
    repoURL: https://github.com/codewithwest/project_platform.git
    path: apps/charts/ginger-helm
    targetRevision: dev
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true