apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: storage
spec:
  encryptedData:
    password: AgA55qV//0Q9oUocz5+6s/AqdU9sSoUs1XqIOWHq9NPGo+jgc5PDtH2OSKqPbD7XlnLMjkrAuMIzRb+RdOHL3dVjH8DLNVO4tqdDHu2RxZT9X2lmjH0nAEU4wmOxlA08N6puuWKKzwLAKk1cRMXdtnjhNg0AUVEDCOd0DzlZ7L/FilV0Azigj7TA6M5FqA7gcRpwnGImM+RklbgriDRPmVe1HLLQ7LyXyO2aEK7+bOp2lXZ7my2o+TgcUMqdjXNjm9ph1WHYFoDzeKzGhCR3M5lL32d2XxhJe6bsTKkD6PDt0x+AsAbxB6CYl8onO9qxXADp8GX6CrPQqh/mP+uA7ecCFIlNhvHPx9oP9b3eN/KzquspEpLvFYr7zpWnh7yxNKYMc7L6QL1Nop3g6Qn7XFLGVE3xxjMRG448LNs2N6ofcLyQuqd5bpJCU5Y0MALjuFJNRv2X47Af6R/f3do/H4HGWshvmhYHySShF9ZbrP9PPzpI5oxbi/nWa3O0GaPIxrEuUb/pzh7dBmrimSWydBMsbVo1wV3uTER6i4+wdZtEz3HuMD0rXydWa1BATE8F8Yt3hhymQKF2joPq+X2ubNu/1a9AOeSFD/Ouv0shYimGZ4vN8KAgBUoyHDvKOXr/ieGn9SWTW9fBh/XscPjzuI7kfAQ4vh/3YVQSpD8Usey2QES4HvkY6L/xZkkCi6rraHxjxBqifY6ciK1dEZDtqrETtxFEXkZzgw==
  template:
    metadata:
      name: postgres-credentials
      namespace: storage
