# ==========================================
# Qdrant Vector Database Deployment Setup
# ==========================================
qdrant:
  replicaCount: 1

  image:
    repository: docker.io/qdrant/qdrant
    tag: "v1.18.2"
    pullPolicy: IfNotPresent

  # -- Expose Qdrant via Nginx Ingress Controller
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      ingress.kubernetes.io/proxy-body-size: "100m"
      nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    hosts:
      - host: qdrant.westdynamics.io
        paths:
          - path: /
            pathType: ImplementationSpecific
            # ADD THIS PORT BLOCK BELOW:
            port: 6333  # Qdrant's default HTTP REST port
    tls:
      - secretName: harbor-tls-secret
        hosts:
          - qdrant.westdynamics.io