apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: management
spec:
  destination:
    name: ''
    namespace: harbor # Harbor should be deployed to its own namespace
    server: 'https://kubernetes.default.svc'
  sources:
    # Source 1: The public Harbor Helm chart repository
    - repoURL: 'https://helm.goharbor.io'
      targetRevision: '1.14.0' # Use a specific, stable chart version
      chart: harbor
      helm:
        valueFiles:
          # Path to the values.yaml file relative to the *values source* root
          - $values/services/harbor/values.yaml
    # Source 2: Your private Git repository containing the values.yaml file.
    - repoURL: 'https://github.com/codewithwest/project_platform.git'
      targetRevision: dev
      ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
