{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ginger.fullname" . }}-ingress
  labels:
    {{- include "ginger.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: {{ include "ginger.fullname" . }}-api
                port:
                  number: {{ .Values.ginger.api.port }}
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: {{ include "ginger.fullname" . }}-api
                port:
                  number: {{ .Values.ginger.api.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "ginger.fullname" . }}-api
                port:
                  number: {{ .Values.ginger.api.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "ginger.fullname" . }}-ui
                port:
                  number: {{ .Values.ginger.ui.port }}
{{- end }}