apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ginger-api-secret
  namespace: { { .Values.global.namespace } }
spec:
  encryptedData:
    LITELLM_MASTER_KEY: "AgACUj2qZJHSr+Pu8qlOfms9fx8SeqwIuFreImAVIdTfh3AGZw24kaNBGc7w/jA+w4qCtJm3NSYoPtfOt3dagad0rBCAph9tiQvNyArFFRj5Lj6gaZc/ieMkmY/RfpFW3TAcojuLMMk4hS49dgiE7qhOfp4vAiJNT+d6KDAKEMjHN0O33uvW7SR0kilOy2gwtSuMzhirSkuVpCJHdUct5x05HFmnVsRm4IFKSLLrJeZI5KWWxawohCrZn2ukuHZpja4rUPO42xb4we2lZsHCSxoahq7W3A7G47C/tmXLAJG67pYhXe17lyN1ofc4DjxDKjwG1KY2tsROvJn6V6mOpirw/wPCK+hIP8FRuOs7rnkFOaiAdQTQ4u1E/BIsPu/tZVIFnAJ5JsJoO9ufK888bd7e2bIejsalfrNbAbVpc0ohPq3PumSErna/gAJdRafe2hj/OBQlU2JpOb8xELjAy9XervFovH4xybi7nftoSKcUy+yUECQ0emVDDTsEAzSLhSO4XMvM4gYsLcJIXAPqLAD6CWc6u18TboA62D7ygQ2myCkVZ6tLTG1ObMEatAgy2JBem2JtOizlpRtL0gvZA3yqBiUsz++3JlDk1txDY+exdYrTFz+glBk2HlD+LmAAKUAsPRQgkUM7/IFyGyeIjiPGKiNAbDJD25gln+qZln/WHDYua1fCi5VqayvUj7d2XUwIxrT+fPB6tQR0Vk6TPaJTBStLIW3mKPrKrQeRb9U3HkV09c8pTkeI81ao/oY="
    LITELLM_PROXY_API_KEY: "AgAU9QgTaD2/1Z99zFleMa0V6HI+8SId7NmJfyeXLAlgIF4lXSRtDLSLFMCpyjkB+CHkoto0jZogg9hmE5voMVWCFeVFTiOeBEFxytTi6jemCHqOymUIz/pYD9HgNV+SZtHMeOs9G6tQ2VUcTDBdR3Qg+ZmqsGG2GmncD5bgON7mAxQiuUwLUxuRgmp5tquvqWu3R4TdS40cNcCsiUexRSWbii0emrY7B8qz853DwLoiYRPvik38+txdFTD2CY7SX1uJk9HJsvgEvemPXS6k6A7Oz3c0c4eh0oshRTs2jT/M0yxY8mPtrfeDv5SBkz4NEKgoWrq4dE1eeKj/o4baD8qiuerugjnadBdbDTlDlbxi18jhDw4UoE3u5rpua6pc6Cv9F/m1NJhA7wLDJ/wtmVSsknaKYwlD7w3ObQYci2h6TANFmwJFb2wAXUffbviqWjqdDoOSSEy+zkOCqwu4ijvF5oRNDPtr9DuidPXrc1VECWh/NYGWEIMKfnRyQUoDHpkIqwMXE2ma1gkw47VsFZy3nQ3L6E1Tq3RTnVOvTvq4b08XT5d9YNvX94LCrvUb77bPfXVRqdKYS0pmC4MPC8xktiKlio/medNbjGWUtZxblSaypIB2jtznxY4KY+ldkubDB0sJtG3iE2gvTMhUfZr/bidfOOdnkfh5KZMaQkK7mxm9PB0grR+8QIn1VoGuPuEuoTI63D7p+uyiJvoiaoA/SRP4ZpQwCDHOlDmZ19E9wZqTRVzQir5idEWdLZY="
  template:
    metadata:
      name: ginger-api-secret
      namespace: { { .Values.global.namespace } }
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ginger-db-credentials
  namespace: { { .Values.global.namespace } }
spec:
  encryptedData:
    url: "AgA9pRFV+4lPtwmxqOvpiaFTbH/LxGF4/SGrmJjjZpkK52xrYTEMnhpr5soK8YrHxqmjPYHYPlQCWWiWJWLABmNnY102lvssf4oKZIZwadngH+mHjLVVIDD0mDGjzol3ZDfIHdYMMCt6pwoAnDrXhdizwh3cUNYAPaaCtpbAI+hykFFCRAv7jfApzNQIWcGVrmz0FVSVqRIcFHf+NYFGv2Bp2bBOTbM4rPFS6igEcmWlnjy9PlZHWlwS5BwCBNUn1/c1wN3ut6rG2VINuQn+QzydoHf23cp2eAwqRMrkcoPo33cZmfejjw3ayNxboKlMADmWun+yjvWCnriHGkuebWcm6m4OawsQ3tNSKlt6i5khT9BNVzVkNb7q2uzVVr+WLNf4OtPEGy2xujeCphzz10n5kCn5ETtjKgbSbNPi+OGmP1q7eXYrG26kJu1S/+bOozlMMesNXwJ+j32tYd76hQIoIe3FWrFRWgoGadSCXeYOaoU8sI0v1udm2jxyJx9XLjPOBD1bsaeKN58KYiV/cwQ4Rjn3YBDR9a53TInOeMSTzER+PhR76Yg4Khw/DOn5NAXHWBuFC1WE8le5XvJygRN40ii2U4+Xjg+EbOb1ZfSCZ3KPUCUNmBbKx1IQKUumd1sPk1qXqkqOacao02Zn4V18EhfJSqRrDX49xcohYvFRVFv2wDP/Iv1Hgbv8fQ6Yrb2gAURJv5ziWYSxB8B976ilJtICHz9DeKSZfqdsBDFoTjeYn6BNHelcpz++AysHR35287Eq3WVhLHFHNA/C53l9wX0WhgmhIYRJfMDespO1dkKl8VJmKUcUWioT/I+vMtV2ibcZj19kTLhq"
  template:
    metadata:
      name: ginger-db-credentials
      namespace: { { .Values.global.namespace } }
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ginger-valkey-credentials
  namespace: { { .Values.global.namespace } }
spec:
  encryptedData:
    url: "AgAdoJ08YTWZO/egQTWzOF/jh+r5LXyHz0t0Eby3qMqZsMFNNazEOMYGFt4bi/Gnt5HPqc07SZ80Uo5Klth92wFJz06LF0pPzSlZgISyK4ERwTsE7NFgmpLo+wtE3WkUdY9TFrJ6M0leD8FUQc39DLn1JO0KRgwX4TTKdSFN5BKqcyCCwC43Reo4jWRfy35PVToZWM+bnS47045ehkejUI+T2KLVczOh8Oo+wLOdme/+rGyY/b4/RCFdcXTiBMNYfDbT7u0dzE8IRswPnA/Kn5PphUlbWv+UqvA2sK4H1RJ2YktMpUY/NQZzU0CcSzjY7cHVukMmt5QUBWcuxpRvmi8d/YtKTqYFG8a6VDEP9XFSCSaX1VOVrzJ97PdDT4U9VU6ev+nXBITUtgVrzfewFEYVH3YnQpzzQzDR/Zdv00JQIRK6w+45WumV7iUFFOG3uClpWWJaAIsQ2JgdfxfaXVzcLL38zVSXyR9iHYFjSJAAH2dEjjJxQhDohAGtYkmKTyf3hWjruznwp46LC+yLh3Co5hfQDi1GdA5wOfaPtwrnUXddbXTSz5jZSMVcE3pbFR0tVN4JYhjYSpoqQ6FMWLRR0xhTYBdqD0UmRSd4ZWPraULC98gnvqjhmwQ3ZOvMItBogUgJjOgMEk2XXo2zVmGEo4HI1tlcOHgnSQziLd7j8lfql1L0UQHgCdOQldgsa+SpqyDj1LW4LyfHx51wCa4EQycXIdTnf1DLDLRR9TTEH0KhJu0HTGKJ5HcNDb84THL4Q4rV+5ID0nlwF+GlB34="
  template:
    metadata:
      name: ginger-valkey-credentials
      namespace: { { .Values.global.namespace } }
