apiVersion: v1
kind: Service
metadata:
  name: {{ include "ginger.fullname" . }}-api
  labels:
    {{- include "ginger.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ginger.api.port }}
      targetPort: {{ .Values.ginger.api.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "ginger.selectorLabels" . | nindent 4 }}
    component: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ginger.fullname" . }}-ui
  labels:
    {{- include "ginger.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.ginger.ui.port }}
      targetPort: {{ .Values.ginger.ui.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "ginger.selectorLabels" . | nindent 4 }}
    component: ui