# Authentication settings
# auth:
#   postgresPassword: "StrongPassword123" # Password for 'postgres' admin
#   username: "my_app_user"                # Custom application user
#   password: "UserPassword456"            # Password for custom user
#   database: "my_application_db"          # Initial database to create

# Persistence settings
primary:
  persistence:
    enabled: true
    size: 5Gi                           # Disk size for the DB
    storageClass: "standard"             # Change to your cloud's storage class (e.g., gp2, standard)

# Resources (CPU/Memory limits)
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
