apiVersion: v2
name: chromadb
description: A Helm chart for ChromaDB vector store deployment
type: application
version: 1.0.0
appVersion: "1.5.3"

dependencies:
  - name: chromadb
    version: 0.2.2
    repository: "https://amikos-tech.github.io/chromadb-chart/"
