replicaCount: 1

image:
  registry: ""
  repository: ghcr.io/chroma-core/chroma
  tag: ""
  digest: ""
  pullPolicy: IfNotPresent

initImage:
  registry: ""
  repository: docker.io/httpd
  tag: "2"
  digest: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

commonLabels: {}
podLabels: {}

serviceAccount:
  create: true
  annotations: {}
  name: ""
  automountServiceAccountToken: true

service:
  type: ClusterIP
  nodePort: null

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
  hosts:
    - host: chromadb.westdynamics.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: chromadb-tls-secret
      hosts:
        - chromadb.westdynamics.io

resources:
  requests:
    cpu: "100m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

podSpec:
  terminationGracePeriodSeconds: 5
  securityContext: {}
  podAnnotations: {}
  annotations: {}
  initContainers: []

readinessProbe:
  failureThreshold: 20
  timeoutSeconds: 10
  periodSeconds: 5

livenessProbe:
  failureThreshold: 40
  timeoutSeconds: 10
  periodSeconds: 5

startupProbe:
  failureThreshold: 1000
  periodSeconds: 5
  initialDelaySeconds: 10

chromadb:
  allowReset: false
  isPersistent: true
  persistDirectory: /data
  logConfigFileLocation: /chroma/log_config.yaml
  logConfigMap: null
  logging:
    root: "INFO"
    chromadb: "DEBUG"
    uvicorn: "INFO"
  anonymizedTelemetry: false
  corsAllowOrigins: []
  serverHost: "0.0.0.0"
  serverHttpPort: 8000
  maxPayloadSizeBytes: "41943040"
  data:
    volumeSize: "10Gi"
    storageClass: null
    accessModes: ["ReadWriteOnce"]
    retentionPolicyOnDelete: "Delete"
  telemetry:
    enabled: false
    endpoint: ""
    serviceName: "chroma"
    filters: []
  sqliteFilename: ""
  sqliteDb:
    hashType: ""
    migrationMode: ""
  circuitBreaker:
    requests: null
  segmentManager:
    hnswIndexPoolCacheConfig: {}
  maintenance:
    collection_cache_policy: null
    collection_cache_limit_bytes: 1000000000
  auth:
    enabled: true
    type: "token"
    existingSecret: ""
    basic:
      username: "chroma"
      password: null
    token:
      headerType: "Authorization"
      value: null
  extraConfig: {}
