apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docs
  namespace: management
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: management
  source:
    repoURL: https://github.com/codewithwest/project_platform.git
    path: apps/charts/docs
    targetRevision: dev
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
