apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-admin-secret
  namespace: management
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: "AgBQ8L3/00lj8a9xOkEP4wj6z5/nOMcdqHBl7dV6L8tuBaq5EH1Tj/STErTooOIxqqQrRa3yjaQSw6IK4FuqEgJl6N9gBfPPMH/BPBB72fegRlIKnjmUdqkyeyAPm2vJ8u6AL6sBsh6HgM0j4w8kCZSKff7Yhv0arupbr0fHITJf+LxADCzTZ1RSk6DefUQS8lYpQO1XltuYXd3A1t3ynFkONLiKMDxKoT6e+bQl8hYXJR4mreyY5TuUjIDYuq4iuyz6+L4qrkg4Q3/rNNB6ybxz8/RITbjjqhytYGvfQOKT40OcwJcg2k5Ew8HG1sisqKdVj2LonH903ksDbvXcZAB8eDh+nphBrVI+7da9ejGYeSKopqJQD18zaMy/m/6Zt7/emwRPIkGTNEFL8tOy7hgiajlPuuuDwDbQPgvSpzDc/OgECYh68vqxNCqEbDokxrFiIuy230rjf++h1VBfmq/1mLs3itehUO0O+1vScsXopufvq8X2pMusZ3g7V47KIkcOC7YGMf/dtGjjUw7rwV/y9+pBpH2Of52LvtNQfVfPyBbuphdfrve0ACEs3JGv5puLow6MjqDNEnUQMVRUAzWHm+bTzsJbDbdQy6eaVV6HZV2Ddo+OltAExqBOmXKobkTMTLNE9b51FMsiunU2JNQzI/Nqf6+lfgx40ebb+hxl//2ROgVNq5vrvuNA+lHc1Gcl81zHL/9aZKzyaLwZgXAMS2GgsvUZDZ93gpRe92b3wriKQ3w="
  template:
    metadata:
      name: harbor-admin-secret
      namespace: management
