apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
spec:
  destination:
    name: ''
    namespace: management
    server: 'https://kubernetes.default.svc'
  sources:
    - path: ''
      repoURL: 'https://charts.jenkins.io'
      targetRevision: x
      chart: jenkins
      helm:
        valueFiles:
          - $values/values.yaml
    - repoURL: 'https://github.com/codewithwest/project_platform.git'
      targetRevision: dev
      ref: values
  project: management
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true