apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: management
spec:
  destination:
    name: ''
    namespace: management
    server: 'https://kubernetes.default.svc'
  sources:
    # Source 1: The public Jenkins Helm chart repository
    - repoURL: 'https://charts.jenkins.io'
      targetRevision: '5.8.83'
      chart: jenkins
      helm:
        valueFiles:
          - $values/values.yaml
    # Source 2: Your private Git repository containing the values.yaml file
    - repoURL: 'https://github.com/codewithwest/project_platform.git'
      targetRevision: dev
      path: services/jenkins # <--- Add the path to your values.yaml file
      ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
