# Source: https://charts.jenkins.io
controller:
  service:
    type: NodePort
    ports:
      - port: 80
        targetPort: 8080
        nodePort: 30081
        name: http
  image:
    tag: 'latest-jdk21'
  persistence:
    enabled: true
    storageClass: "standard"
    size: 5Gi
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  installPlugins:
    - kubernetes:latest
    - git:latest
    - blueocean:latest 
    - docker-workflow:latest 
    - junit:latest
    - apache-httpcomponents-client-4-api:latest
    - credentials:latest    
    - branch-api:latest
    - theme-manager:latest
  startupProbe:
    initialDelaySeconds: 120
    periodSeconds: 30
    failureThreshold: 10
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
        type: Socket
  volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
