# Source: https://charts.jenkins.io
controller:
  serviceType: ClusterIP
  image:
    tag: 'latest-jdk21'
  persistence:
    enabled: true
    storageClass: "standard" # Use a storage class if available, otherwise Minikube's default will work
    size: 5Gi
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  # You can specify custom plugins here
  installPlugins:
    - kubernetes:latest
    - git:latest
    - blueocean:latest 
    - docker-workflow:latest 
    - junit:latest
    - apache-httpcomponents-client-4-api:latest
    - credentials:latest    
    - branch-api:latest
    - theme-manager:latest
  startupProbe:
    initialDelaySeconds: 120 # Wait 120 seconds before starting the checks
    periodSeconds: 30       # Check every 30 seconds thereafter
    failureThreshold: 10 
  # controller:
  # ... other controller settings ...
  # Add the volumes block to define the hostPath volume
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
        type: Socket
  # Add the volumeMounts block to mount the volume into the Jenkins container
  volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
