podTemplate(
  label: 'docker-agent',
  containers: [
    containerTemplate(
      name: 'docker',
      image: 'docker:28-cli',
      command: 'cat',
      ttyEnabled: true
    )
  ],
  volumes: [
    hostPathVolume(
      hostPath: '/var/run/docker.sock',
      mountPath: '/var/run/docker.sock'
    )
  ]
) {
  node('docker-agent') {

    stage('Check Docker Access') {
      container('docker') {
        sh 'docker version'
      }
    }

    stage('Clone repo via checkout scm') {
        container('docker') {
            sh '''
                git clone https://github.com/codewithwest/project_platform.git
                cd project_platform
                git checkout dev

                ls -la
            '''
        }
    }

    stage('Build Docker Image') {
      container('docker') {
        sh '''
          cd project_platform
          docker build -f Dockerfile.jenkins -t jenkins:latest .
        '''
      }
    }
  }
}
