apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-pod-reader
  namespace: management
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["controllerrevisions"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-pod-reader-binding
  namespace: management
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-pod-reader
subjects:
  - kind: ServiceAccount
    name: argocd-server
    namespace: management
